name: Build tailwindcss

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup_node@v2
      - run: npm ci
      - run: npm install -D tailwindcss
      - run: npx tailwindcss -i ./styles/in.css -o ./styles/out.css